name: chiltepin-env

channels:
  - conda-forge

dependencies:
  - python
  - pytest=7.4.0
  - pip
  - flux-core=0.52.0
  - flux-sched=0.28.0
  - openmpi
  - openmpi-mpicc
  - openmpi-mpicxx
  - openmpi-mpifort
  - pip:
    - parsl[monitoring]==2023.12.4
