services:
  slurmfrontend:
        build:
          context: ./
#          cache_from:
#                - type=registry,ref=ghcr.io/noaa-gsl/exascaleworkflowsandbox/frontend:cache,mode=max
          dockerfile: ./frontend/Dockerfile
        image: ghcr.io/noaa-gsl/exascaleworkflowsandbox/frontend:latest
        container_name: frontend
        hostname: slurmfrontend
        user: admin
        volumes:
                - shared-vol:/home/admin
                - opt-vol:/opt
                - ./test:/home/admin/test
        ports:
                - 8888:8888
  slurmmaster:
        build:
          context: ./
          dockerfile: ./master/Dockerfile
        image: ghcr.io/noaa-gsl/exascaleworkflowsandbox/master:latest
        container_name: master
        hostname: slurmmaster
        user: admin
        volumes:
                - shared-vol:/home/admin
                - opt-vol:/opt:ro
                - ./test:/home/admin/test
        environment:
                - SLURM_CPUS_ON_NODE=8
        ports:
                - 6817:6817
                - 6818:6818
                - 6819:6819
  slurmnode1:
        build:
          context: ./
          dockerfile: ./node/Dockerfile
        image: ghcr.io/noaa-gsl/exascaleworkflowsandbox/node:latest
        container_name: node1
        hostname: slurmnode1
        user: admin
        volumes:
                - shared-vol:/home/admin
                - opt-vol:/opt:ro
                - ./test:/home/admin/test
        environment:
                - SLURM_NODENAME=slurmnode1
                - SLURM_CPUS_ON_NODE=8
        links:
                - slurmmaster
  slurmnode2:
        build:
          context: ./
          dockerfile: ./node/Dockerfile
        image: ghcr.io/noaa-gsl/exascaleworkflowsandbox/node:latest
        container_name: node2
        hostname: slurmnode2
        user: admin
        volumes:
                - shared-vol:/home/admin
                - opt-vol:/opt:ro
                - ./test:/home/admin/test
        environment:
                - SLURM_NODENAME=slurmnode2
                - SLURM_CPUS_ON_NODE=8
        links:
                - slurmmaster
  slurmnode3:
        build:
          context: ./
          dockerfile: ./node/Dockerfile
        image: ghcr.io/noaa-gsl/exascaleworkflowsandbox/node:latest
        container_name: node3
        hostname: slurmnode3
        user: admin
        volumes:
                - shared-vol:/home/admin
                - opt-vol:/opt:ro
                - ./test:/home/admin/test
        environment:
                - SLURM_NODENAME=slurmnode3
                - SLURM_CPUS_ON_NODE=8
        links:
                - slurmmaster
volumes:
        shared-vol:
        opt-vol:
