services:
  slurmfrontend:
        build:
          context: ./
          dockerfile: ./frontend/Dockerfile
        image: noaagsl/exaworkflow-frontend:latest
        container_name: exaworkflow-frontend
        shm_size: '4g'
        hostname: slurmfrontend
        user: admin
        volumes:
                - shared-vol:/home/admin
                - opt-vol:/opt
                - ./test:/home/admin/test
        ports:
                - 8888:8888
  slurmmaster:
        build:
          context: ./
          dockerfile: ./master/Dockerfile
        image: noaagsl/exaworkflow-master:latest
        container_name: exaworkflow-master
        shm_size: '4g'
        hostname: slurmmaster
        user: admin
        volumes:
                - shared-vol:/home/admin
                - opt-vol:/opt:ro
                - ./test:/home/admin/test
        environment:
                - SLURM_CPUS_ON_NODE=8
        ports:
                - 6817:6817
                - 6818:6818
                - 6819:6819
  slurmnode1:
        build:
          context: ./
          dockerfile: ./node/Dockerfile
        image: noaagsl/exaworkflow-node:latest
        container_name: exaworkflow-node1
        shm_size: '4g'
        hostname: slurmnode1
        user: admin
        volumes:
                - shared-vol:/home/admin
                - opt-vol:/opt:ro
                - ./test:/home/admin/test
        environment:
                - SLURM_NODENAME=slurmnode1
                - SLURM_CPUS_ON_NODE=8
        links:
                - slurmmaster
  slurmnode2:
        build:
          context: ./
          dockerfile: ./node/Dockerfile
        image: noaagsl/exaworkflow-node:latest
        container_name: exaworkflow-node2
        shm_size: '4g'
        hostname: slurmnode2
        user: admin
        volumes:
                - shared-vol:/home/admin
                - opt-vol:/opt:ro
                - ./test:/home/admin/test
        environment:
                - SLURM_NODENAME=slurmnode2
                - SLURM_CPUS_ON_NODE=8
        links:
                - slurmmaster
  slurmnode3:
        build:
          context: ./
          dockerfile: ./node/Dockerfile
        image: noaagsl/exaworkflow-node:latest
        container_name: exaworkflow-node3
        shm_size: '4g'
        hostname: slurmnode3
        user: admin
        volumes:
                - shared-vol:/home/admin
                - opt-vol:/opt:ro
                - ./test:/home/admin/test
        environment:
                - SLURM_NODENAME=slurmnode3
                - SLURM_CPUS_ON_NODE=8
        links:
                - slurmmaster
volumes:
        shared-vol:
        opt-vol:
