mirrors:
  s3_spack_stack_buildcache_rw:
    url: s3://chiltepin-us-east-2/spack-stack/
    access_pair:
      - $S3_BUILD_CACHE_KEY
      - $S3_BUILD_CACHE_SECRET_KEY
    access_token: $S3_BUILD_CACHE_TOKEN
