hercules-env: &hercules-env
  environment:
    - "module purge"
    - "module use /work/noaa/epic/role-epic/spack-stack/hercules/spack-stack-1.7.0/envs/ue-intel/install/modulefiles/Core"
    - "module load stack-intel/2021.9.0"
    - "module load stack-intel-oneapi-mpi/2021.9.0"
    - "module load stack-python/3.10.13"
    - "module load jedi-mpas-env"
    - "module unload py-attrs"
    - "export CHILTEPIN_MPIF90=$MPIF90"
    - "ulimit -s unlimited || true"

hera-env: &hera-env
  environment:
    - "module purge"
    - "module use /scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.7.0/envs/ue-intel/install/modulefiles/Core"
    - "module load stack-intel/2021.5.0"
    - "module load stack-intel-oneapi-mpi/2021.5.1"
    - "module load stack-python/3.10.13"
    - "module load jedi-mpas-env"
    - "export CHILTEPIN_MPIF90=$MPIF90"

docker-env: &docker-env
  environment:
    - "source /usr/lmod/lmod/init/bash"
    - "module use /opt/spack-stack/envs/unified-env/install/modulefiles/Core"
    - "module load stack-gcc"
    - "module load stack-openmpi"
    - "module load stack-python"
    - "module load jedi-mpas-env"
    - "module unload py-attrs"
    - "export CHILTEPIN_MPIF90=$MPIF90"

hercules:
  resources:
    mpi:
      mpi: True
      max_mpi_apps: 2
      mpi_launcher: "srun"
      provider: "slurm"
      cores_per_node: 80
      nodes_per_block: 3
      exclusive: True
      partition: "hercules"
      account: "gsd-hpcs"
      walltime: "1:00:00"
      <<: *hercules-env
    service:
      mpi: False
      provider: "slurm"
      cores_per_node: 1
      nodes_per_block: 1
      exclusive: False
      partition: "service"
      account: "gsd-hpcs"
      walltime: "1:00:00"
      <<: *hercules-env
    compute:
      mpi: False
      provider: "slurm"
      cores_per_node: 80
      nodes_per_block: 1
      exclusive: True
      partition: "hercules"
      account: "gsd-hpcs"
      walltime: "1:00:00"
      <<: *hercules-env

hera:
  resources:
    mpi:
      mpi: True
      max_mpi_apps: 2
      mpi_launcher: "srun"
      provider: "slurm"
      cores_per_node: 40
      nodes_per_block: 3
      exclusive: True
      partition: "hera"
      account: "gsd-hpcs"
      walltime: "1:00:00"
      <<: *hera-env
    service:
      mpi: False
      provider: "slurm"
      cores_per_node: 1
      nodes_per_block: 1
      exclusive: False
      partition: "service"
      account: "gsd-hpcs"
      walltime: "1:00:00"
      <<: *hera-env
    compute:
      mpi: False
      provider: "slurm"
      cores_per_node: 40
      nodes_per_block: 1
      exclusive: True
      partition: "hera"
      account: "gsd-hpcs"
      walltime: "1:00:00"
      <<: *hera-env
  

docker:
  resources:
    mpi:
      mpi: True
      max_mpi_apps: 2
      mpi_launcher: "srun"
      provider: "slurm"
      cores_per_node: 8
      nodes_per_block: 3
      exclusive: True
      partition: "slurmpar"
      account: ""
      walltime: "1:00:00"
      <<: *docker-env
    service:
      mpi: False
      provider: "slurm"
      cores_per_node: 1
      nodes_per_block: 1
      exclusive: False
      partition: "slurmpar"
      account: ""
      walltime: "1:00:00"
      <<: *docker-env
    compute:
      mpi: False
      provider: "slurm"
      cores_per_node: 8
      nodes_per_block: 1
      exclusive: True
      partition: "slurmpar"
      account: ""
      walltime: "1:00:00"
      <<: *docker-env
