ARG OS=ubuntu20

# Create a build-cache of flux
FROM noaagsl/spack-flux-${OS}:latest AS flux
RUN set -ex \
    && cd /opt/scripts \
    && . /opt/spack/share/spack/setup-env.sh \
    && rm -rf /opt/spack/opt/spack/gpg \
    && spack env activate flux \
    && ./make_buildcache.sh /opt/mirrors flux

# Add the flux mirror
FROM noaagsl/spack-base-${OS}:latest AS exaworks-flux
COPY --from=flux /opt/mirrors/flux_mirror /opt/mirrors/flux_mirror

# Create a build-cache of radical
FROM noaagsl/spack-radical-${OS}:latest AS radical
RUN set -ex \
    && cd /opt/scripts \
    && . /opt/spack/share/spack/setup-env.sh \
    && rm -rf /opt/spack/opt/spack/gpg \
    && spack env activate radical \
    && ./make_buildcache.sh /opt/mirrors radical

# Add the radical mirror
FROM exaworks-flux AS exaworks-radical
COPY --from=radical /opt/mirrors/radical_mirror /opt/mirrors/radical_mirror

# Create a build-cache of stc
FROM noaagsl/spack-stc-${OS}:latest AS stc
RUN set -ex \
    && cd /opt/scripts \
    && . /opt/spack/share/spack/setup-env.sh \
    && rm -rf /opt/spack/opt/spack/gpg \
    && spack env activate stc \
    && ./make_buildcache.sh /opt/mirrors stc

# Add the stc mirror
FROM exaworks-radical AS exaworks-stc
COPY --from=stc /opt/mirrors/stc_mirror /opt/mirrors/stc_mirror

# Create a build-cache of parsl
FROM noaagsl/spack-parsl-${OS}:latest AS parsl
RUN set -ex \
    && cd /opt/scripts \
    && . /opt/spack/share/spack/setup-env.sh \
    && rm -rf /opt/spack/opt/spack/gpg \
    && spack env activate parsl \
    && ./make_buildcache.sh /opt/mirrors parsl

# Add the parsl mirror
FROM exaworks-stc AS exaworks-parsl
COPY --from=parsl /opt/mirrors/parsl_mirror /opt/mirrors/parsl_mirror

# Install exaworks from the mirrors
FROM exaworks-parsl as exaworks
RUN set -ex \
    && cd /opt/scripts \
    && . /opt/spack/share/spack/setup-env.sh \
    && ./activate_buildcache.sh /opt/mirrors flux \
    && ./activate_buildcache.sh /opt/mirrors radical \
    && ./activate_buildcache.sh /opt/mirrors stc \
    && ./activate_buildcache.sh /opt/mirrors parsl \
    && ./install_flux.sh \
    && ./install_radical.sh \
    && ./install_stc.sh \
    && ./install_parsl.sh \
    && ./install_exaworks.sh \
    && rm -rf /opt/spack/var/spack/cache/_source-cache \
    && rm -rf /opt/mirrors

CMD ["/bin/bash"]
