FROM centos:7.7.1908

ENV PATH "/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/bin"

RUN set -ex \
    && yum makecache fast \
    && yum -y update \
    && yum -y install epel-release \
    && yum -y install \
         autoconf \
	 bash-completion \
	 bzip2 \
	 bzip2-devel \
	 file \
	 gcc \
	 gcc-c++ \
	 git \
	 libffi-devel \
	 make \
	 openssl-devel \
	 patch \
	 unzip \
	 vim \
	 wget \
	 which \
	 xz-devel \
	 zlib-devel

RUN set -ex \
    && cd /tmp \
    && wget https://www.python.org/ftp/python/3.7.11/Python-3.7.11.tgz \
    && tar xzf Python-3.7.11.tgz \
    && pushd Python-3.7.11 \
    && ./configure --enable-optimizations \
    && make install \
    && popd \
    && rm -rf Python-3.7.11.tgz Python-3.7.11

COPY scripts/* /tmp

RUN set -ex \
    && cd /tmp \
    && ./install_spack.sh /opt/spack-0.19.1 v0.19.1

RUN set -ex \
    && cd /tmp \
    && . /opt/spack-0.19.1/share/spack/setup-env.sh \
    && ./install_exaworks.sh /opt/exaworks-mirror \
    && rm -rf /opt/exaworks-mirror /opt/spack-0.19.1/var/spack/cache/_source-cache

RUN mkdir -p /opt/test

COPY test/* /opt/test

CMD ["/bin/bash"]