# Create a buildcache of base
FROM noaagsl/spack-base-ubuntu20:latest AS base
RUN set -ex \
    && cd /tmp \
    && . /opt/spack/share/spack/setup-env.sh \
    && rm -rf /opt/spack/opt/spack/gpg \
    && spack env activate base \
    && ./make_buildcache.sh /opt/mirrors bootstrap \
    && ./make_buildcache.sh /opt/mirrors base

# Copy the base mirrors in
FROM noaagsl/spack-base-ubuntu20:latest AS exaworks-base
COPY --from=base /opt/mirrors/bootstrap_mirror /opt/mirrors/bootstrap_mirror
COPY --from=base /opt/mirrors/base_mirror /opt/mirrors/base_mirror

# Create a build-cache of flux
FROM noaagsl/spack-flux-ubuntu20:latest AS flux
RUN set -ex \
    && cd /tmp \
    && . /opt/spack/share/spack/setup-env.sh \
    && rm -rf /opt/spack/opt/spack/gpg \
    && spack env activate flux \
    && ./make_buildcache.sh /opt/mirrors flux

# Add the flux mirror
FROM exaworks-base AS exaworks-flux
COPY --from=flux /opt/mirrors/flux_mirror /opt/mirrors/flux_mirror

# Create a build-cache of radical
FROM noaagsl/spack-radical-ubuntu20:latest AS radical
RUN set -ex \
    && cd /tmp \
    && . /opt/spack/share/spack/setup-env.sh \
    && rm -rf /opt/spack/opt/spack/gpg \
    && spack env activate radical \
    && ./make_buildcache.sh /opt/mirrors radical

# Add the radical mirror
FROM exaworks-flux AS exaworks-radical
COPY --from=radical /opt/mirrors/radical_mirror /opt/mirrors/radical_mirror

# Create a build-cache of stc
FROM noaagsl/spack-stc-ubuntu20:latest AS stc
RUN set -ex \
    && cd /tmp \
    && . /opt/spack/share/spack/setup-env.sh \
    && rm -rf /opt/spack/opt/spack/gpg \
    && spack env activate stc \
    && ./make_buildcache.sh /opt/mirrors stc

# Add the stc mirror
FROM exaworks-radical AS exaworks-stc
COPY --from=stc /opt/mirrors/stc_mirror /opt/mirrors/stc_mirror

# Create a build-cache of parsl
FROM noaagsl/spack-parsl-ubuntu20:latest AS parsl
RUN set -ex \
    && cd /tmp \
    && . /opt/spack/share/spack/setup-env.sh \
    && rm -rf /opt/spack/opt/spack/gpg \
    && spack env activate parsl \
    && ./make_buildcache.sh /opt/mirrors parsl

# Add the parsl mirror
FROM exaworks-stc AS exaworks-parsl
COPY --from=parsl /opt/mirrors/parsl_mirror /opt/mirrors/parsl_mirror

# Install exaworks from the mirrors
FROM exaworks-parsl as exaworks
RUN set -ex \
    && cd /tmp \
    && . /opt/spack/share/spack/setup-env.sh \
    && ./activate_buildcache.sh /opt/mirrors bootstrap \
    && ./activate_buildcache.sh /opt/mirrors base \
    && ./activate_buildcache.sh /opt/mirrors flux \
    && ./activate_buildcache.sh /opt/mirrors radical \
    && ./activate_buildcache.sh /opt/mirrors stc \
    && ./activate_buildcache.sh /opt/mirrors parsl \
    && ./install_exaworks.sh \
    && rm -rf /opt/spack/var/spack/cache/_source-cache \
    && rm -rf /opt/mirrors

CMD ["/bin/bash"]
