ARG OS=ubuntu20
FROM noaagsl/spack-base-${OS}:latest

COPY scripts/* /opt/scripts/

# Install flux Spack packages
RUN set -ex \
    && cd /opt/scripts \
    && . /opt/spack/share/spack/setup-env.sh \
    && ./install_flux.sh \
    && rm -rf /opt/spack/var/spack/cache/_source-cache

CMD ["/bin/bash"]
