name: ExascaleSandboxTests

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Prune pre-loaded GHA docker images
        run: |
          docker images
          docker image prune -a -f
          docker images
      -
        name: Build frontend
        uses: docker/build-push-action@v4
        with:
          context: ./docker
          file: ./docker/frontend/Dockerfile
          push: false
          load: true
          tags: ghcr.io/noaa-gsl/exascaleworkflowsandbox/frontend:latest
          cache-from: type=registry,ref=ghcr.io/noaa-gsl/exascaleworkflowsandbox/frontend:cache
          cache-to: type=registry,ref=ghcr.io/noaa-gsl/exascaleworkflowsandbox/frontend:cache,mode=max
      -
        name: Build master
        uses: docker/build-push-action@v4
        with:
          context: ./docker
          file: ./docker/master/Dockerfile
          push: false
          load: true
          tags: ghcr.io/noaa-gsl/exascaleworkflowsandbox/master:latest
          cache-from: type=registry,ref=ghcr.io/noaa-gsl/exascaleworkflowsandbox/master:cache
          cache-to: type=registry,ref=ghcr.io/noaa-gsl/exascaleworkflowsandbox/master:cache,mode=max
      -
        name: Build node
        uses: docker/build-push-action@v4
        with:
          context: ./docker
          file: ./docker/node/Dockerfile
          push: false
          load: true
          tags: ghcr.io/noaa-gsl/exascaleworkflowsandbox/node:latest
          cache-from: type=registry,ref=ghcr.io/noaa-gsl/exascaleworkflowsandbox/node:cache
          cache-to: type=registry,ref=ghcr.io/noaa-gsl/exascaleworkflowsandbox/node:cache,mode=max
      -
        name: Start Slurm cluster containers
        run: |
          cd docker
          export DOCKER_CLIENT_TIMEOUT=600
          export COMPOSE_HTTP_TIMEOUT=600
          docker compose version
          docker compose config
          docker images
          docker ps -a
          docker compose -f docker-compose.yml up -d --no-build
      -
        name: Copy test files to work directory
        run: |
          docker exec frontend bash -l -c "mkdir -p work; cd work ; cp -r ../test/* ."
      -
        name: Parsl hello test
        run: |
          docker exec frontend bash -l -c "cd work/src ; ./parsl_hello.py"
          docker exec frontend bash -l -c "diff work/src/parsl_python_hello.out work/output/parsl_python_hello.out.baseline"
          docker exec frontend bash -l -c "diff work/src/parsl_bash_hello.out work/output/parsl_bash_hello.out.baseline"
      -
        name: Parsl/Flux hello MPI test
        run: |
          docker exec frontend bash -l -c "cd work/src ; ./parsl_flux_mpi_hello.py"
          docker exec frontend bash -l -c "diff work/src/parsl_flux_resource_list.txt work/output/parsl_flux_resource_list.txt.baseline"
          docker exec frontend bash -l -c "diff work/src/parsl_flux_mpi_hello_compile.out work/output/parsl_flux_mpi_hello_compile.out.baseline"
          docker exec frontend bash -l -c "diff work/src/parsl_flux_mpi_hello_run.out work/output/parsl_flux_mpi_hello_run.out.baseline"
      -
        name: Debug session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
        timeout-minutes: 60
        with:
          limit-access-to-actor: true
      -
        name: Shut down Slurm cluster containers
        run: |
          cd docker
          export DOCKER_CLIENT_TIMEOUT=600
          export COMPOSE_HTTP_TIMEOUT=600
          docker compose -f docker-compose.yml down
      -
        name: Push frontend
        uses: docker/build-push-action@v4
        with:
          context: ./docker
          file: ./docker/frontend/Dockerfile
          push: true
          tags: ghcr.io/noaa-gsl/exascaleworkflowsandbox/frontend:latest
          cache-from: type=registry,ref=ghcr.io/noaa-gsl/exascaleworkflowsandbox/frontend:cache
          cache-to: type=registry,ref=ghcr.io/noaa-gsl/exascaleworkflowsandbox/frontend:cache,mode=max
      -
        name: Push master
        uses: docker/build-push-action@v4
        with:
          context: ./docker
          file: ./docker/master/Dockerfile
          push: true
          tags: ghcr.io/noaa-gsl/exascaleworkflowsandbox/master:latest
          cache-from: type=registry,ref=ghcr.io/noaa-gsl/exascaleworkflowsandbox/master:cache
          cache-to: type=registry,ref=ghcr.io/noaa-gsl/exascaleworkflowsandbox/master:cache,mode=max
      -
        name: Push node
        uses: docker/build-push-action@v4
        with:
          context: ./docker
          file: ./docker/node/Dockerfile
          push: true
          tags: ghcr.io/noaa-gsl/exascaleworkflowsandbox/node:latest
          cache-from: type=registry,ref=ghcr.io/noaa-gsl/exascaleworkflowsandbox/node:cache
          cache-to: type=registry,ref=ghcr.io/noaa-gsl/exascaleworkflowsandbox/node:cache,mode=max
