# SPDX-License-Identifier: Apache-2.0

name: Documentation

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v4
      -
        name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      -
        name: Install package and documentation dependencies
        run: |
          pip install .[docs]
      -
        name: Build documentation
        run: |
          cd docs
          sphinx-build -W --keep-going -b html . _build/html
