name: Install ExaWorks
# triggered events (push, pull_request) for the develop branch
on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]
  workflow_dispatch:

jobs:

  install_spack:
    name: Install Spack
    runs-on: ubuntu-latest
    env:
      spack_version: v0.19.1

    steps:
      - name: Checkout repository (and LFS objects)
        uses: actions/checkout@v2

      
      - name: Install Spack
        run: |
          ExaWorks/scripts/install_spack.sh $HOME/opt/spack-$spack_version $spack_version

      - name: Install ExaWorks SDK
        run: |
          . $HOME/opt/spack-$spack_version/share/spack/setup-env.sh
          ExaWorks/scripts/install_exaworks.sh $HOME/opt/exaworks-mirror

      - name: Setup tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true
        timeout-minutes: 30