name: Install ExaWorks
# triggered events (push, pull_request) for the develop branch
on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]
  workflow_dispatch:

jobs:

  install_spack:
    name: Install Spack
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository (and LFS objects)
        uses: actions/checkout@v2

      
      - name: Install Spack
        run: |
          ExaWorks/scripts/install_spack.sh $HOME/opt

      - name: Install ExaWorks SDK
        run: |
          . $HOME/opt/spack/share/spack/setup-env.sh
          gcc --version
          ExaWorks/scripts/install_exaworks.sh $HOME/opt/exaworks-mirror
