name: Exaworks Examples
# triggered events (push, pull_request) for the develop branch
on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]
  workflow_dispatch:

jobs:

  exaworks_ubuntu_examples:

    name: Run Exaworks Ubuntu Examples
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get the exaworks-ubuntu20 container
        run: docker pull noaagsl/exaworks-ubuntu20

      - name: Start the exaworks-ubuntu20 container
        run: docker run -d -t --name exaworks-ubuntu20 noaagsl/exaworks-ubuntu20

      - name: Test examples
        run: docker exec exaworks-ubuntu20 bash -c ". /opt/spack-0.19.1/share/spack/setup-env.sh; spack env activate exaworkssdk; cd /opt/test; ./parsl_hello.py"

  exaworks_centos_examples:

    name: Run Exaworks CentOS Examples
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get the exaworks-centos7 container
        run: docker pull noaagsl/exaworks-centos7

      - name: Start the exaworks-centos7 container
        run: docker run -d -t --name exaworks-centos7 noaagsl/exaworks-centos7

      - name: Test examples
        run: docker exec exaworks-centos7 bash -c ". /opt/spack-0.19.1/share/spack/setup-env.sh; spack env activate exaworkssdk; cd /opt/test; ./parsl_hello.py"
