name: ExascaleSandboxTests

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]
  workflow_dispatch:

env:
  REGISTRY_IMAGE: ghcr.io/noaa-gsl/exascaleworkflowsandbox/spack-stack-gnu-openmpi
  AWS_REGION: us-east-2

jobs:
  lint-check:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v4
      -
        name: Format Check
        run:  |
          pip install flake8 black isort
          flake8 src tests
          black src tests --check --diff
          isort src tests --check --diff --profile black


  build-and-test-chiltepin:
    runs-on: ubuntu2204-16c-64g-600ssd
    timeout-minutes: 360
    permissions:
      packages: write
      contents: read
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          logout: false
      -
        name: Prune pre-loaded GHA docker images
        run: |
          docker images
          docker image prune -a -f
          docker images
      -
        name: Start Slurm cluster containers
        run: |
          cd docker
          export DOCKER_CLIENT_TIMEOUT=600
          export COMPOSE_HTTP_TIMEOUT=600
          docker compose version
          docker compose config
          docker images
          docker ps -a
          docker compose -f docker-compose.yml up -d --no-build
      -
        name: Copy test files to work directory
        run: |
          docker exec frontend bash -l -c "mkdir -p work; cd work ; cp -r ../chiltepin/* ."
      -
        name: Install chiltepin package
        run: docker exec frontend bash -l -c "cd work ; pip install -e ."
      -
        name: Run test suite
        run: |
          docker exec frontend bash -l -c "cd work/apps/mpas/bin ; PYTHONPATH=../../../ ./experiment.py ../config/user_config.yaml"
      -
        name: Debug session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
        timeout-minutes: 60
        with:
          limit-access-to-actor: true
      -
        name: Shut down Slurm cluster containers
        run: |
          cd docker
          export DOCKER_CLIENT_TIMEOUT=600
          export COMPOSE_HTTP_TIMEOUT=600
          docker compose -f docker-compose.yml down
