name: ExascaleSandboxTests

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]
  workflow_dispatch:

jobs:
  cleanup-packages:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      -
        name: Remove untagged versions of exascaleworkflowsandbox/spack-stack-gnu-openmpi
        uses: actions/delete-package-versions@v4
        with: 
          package-name: 'exascaleworkflowsandbox/spack-stack-gnu-openmpi'
          package-type: 'container'
<<<<<<< HEAD
          min-versions-to-keep: 0
=======
          min-versions-to-keep: 1
>>>>>>> 8d44464 (Add GitHub workflow to remove untagged container packages)
          delete-only-untagged-versions: 'true'
      -
        name: Remove untagged versions of exascaleworkflowsandbox/frontend
        uses: actions/delete-package-versions@v4
        with: 
          package-name: 'exascaleworkflowsandbox/frontend'
          package-type: 'container'
<<<<<<< HEAD
          min-versions-to-keep: 0
=======
          min-versions-to-keep: 1
>>>>>>> 8d44464 (Add GitHub workflow to remove untagged container packages)
          delete-only-untagged-versions: 'true'
      -
        name: Remove untagged versions of exascaleworkflowsandbox/master
        uses: actions/delete-package-versions@v4
        with: 
          package-name: 'exascaleworkflowsandbox/master'
          package-type: 'container'
<<<<<<< HEAD
          min-versions-to-keep: 0
=======
          min-versions-to-keep: 1
>>>>>>> 8d44464 (Add GitHub workflow to remove untagged container packages)
          delete-only-untagged-versions: 'true'
      -
        name: Remove untagged versions of exascaleworkflowsandbox/node
        uses: actions/delete-package-versions@v4
        with: 
          package-name: 'exascaleworkflowsandbox/node'
          package-type: 'container'
<<<<<<< HEAD
          min-versions-to-keep: 0
=======
          min-versions-to-keep: 1
>>>>>>> 8d44464 (Add GitHub workflow to remove untagged container packages)
          delete-only-untagged-versions: 'true'
      -
        name: Remove untagged versions of exascaleworkflowsandbox/flux-cache-amd64
        uses: actions/delete-package-versions@v4
        with: 
          package-name: 'exascaleworkflowsandbox/flux-cache-amd64'
          package-type: 'container'
<<<<<<< HEAD
          min-versions-to-keep: 0
=======
          min-versions-to-keep: 1
>>>>>>> 8d44464 (Add GitHub workflow to remove untagged container packages)
          delete-only-untagged-versions: 'true'
      -
        name: Remove untagged versions of exascaleworkflowsandbox/flux-cache-arm64
        uses: actions/delete-package-versions@v4
        with: 
          package-name: 'exascaleworkflowsandbox/flux-cache-arm64'
          package-type: 'container'
<<<<<<< HEAD
          min-versions-to-keep: 0
=======
          min-versions-to-keep: 1
>>>>>>> 8d44464 (Add GitHub workflow to remove untagged container packages)
          delete-only-untagged-versions: 'true'
      -
        name: Remove untagged versions of exascaleworkflowsandbox/spack-stack-gnu-openmpi-cache-amd64
        uses: actions/delete-package-versions@v4
        with: 
          package-name: 'exascaleworkflowsandbox/spack-stack-gnu-openmpi-cache-amd64'
          package-type: 'container'
<<<<<<< HEAD
          min-versions-to-keep: 0
=======
          min-versions-to-keep: 1
>>>>>>> 8d44464 (Add GitHub workflow to remove untagged container packages)
          delete-only-untagged-versions: 'true'
      -
        name: Remove untagged versions of exascaleworkflowsandbox/spack-stack-gnu-openmpi-cache-arm64
        uses: actions/delete-package-versions@v4
        with: 
          package-name: 'exascaleworkflowsandbox/spack-stack-gnu-openmpi-cache-arm64'
          package-type: 'container'
<<<<<<< HEAD
          min-versions-to-keep: 0
=======
          min-versions-to-keep: 1
>>>>>>> 8d44464 (Add GitHub workflow to remove untagged container packages)
          delete-only-untagged-versions: 'true'
